version: '3'

services:
  sqlos:
    image: mysql:5.7
    volumes:
      - sql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: piyush
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb

  joomlaos:
    image: joomla:3.9-php7.2-apache
    restart: always
    depends_on:
       - sqlos
    ports:
      - 1234:80
    environment:
      JOOMLA_DB_HOST: sqlos
      JOOMLA_DB_USER: piyush
      JOOMLA_DB_PASSWORD: redhat
      JOOMLA_DB_NAME: mydb
    volumes:
      - joomla_storage_new:/var/www/html

volumes:
   sql_storage_new:
   joomla_storage_new:
